name: CI

on:
  push:
    branches:
      - main

jobs:
  build-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Client
        run: |
          cd "./client"
          echo ${{ secrets.CI_REGISTRY_PASSWORD }} | docker login -u ${{ secrets.CI_REGISTRY_USER }} --password-stdin ${{ secrets.DOCKER_REGISTRY }}
          docker build -t ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.CLIENT_IMAGE_NAME }} .
          docker push ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.CLIENT_IMAGE_NAME }}

  build-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Server
        run: |
          cd "./server"
          echo ${{ secrets.CI_REGISTRY_PASSWORD }} | docker login -u ${{ secrets.CI_REGISTRY_USER }} --password-stdin ${{ secrets.DOCKER_REGISTRY }}
          docker build -t ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.SERVER_IMAGE_NAME }} .
          docker push ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.SERVER_IMAGE_NAME }}

  publish-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Publish Client
        run: |
          cd "./client"
          echo ${{ secrets.CI_REGISTRY_PASSWORD }} | docker login -u ${{ secrets.CI_REGISTRY_USER }} --password-stdin ${{ secrets.DOCKER_REGISTRY }}
          docker pull ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.CLIENT_IMAGE_NAME }}

  publish-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Publish Server
        run: |
          cd "./server"
          echo ${{ secrets.CI_REGISTRY_PASSWORD }} | docker login -u ${{ secrets.CI_REGISTRY_USER }} --password-stdin ${{ secrets.DOCKER_REGISTRY }}
          docker pull ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.SERVER_IMAGE_NAME }}
